export const teamMembers = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@agency.com',
    role: 'Project Manager',
    skills: ['Project Management', 'Client Relations', 'Agile', 'Scrum'],
    availability: 'medium' as const,
    activeProjects: 5,
    initials: 'JD',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@agency.com',
    role: 'UX Designer',
    skills: ['UI Design', 'User Research', 'Wireframing', 'Figma', 'Adobe XD'],
    availability: 'high' as const,
    activeProjects: 4,
    avatar: '/placeholder-avatar.jpg',
    initials: 'SJ',
  },
  {
    id: '3',
    name: 'Mike Thompson',
    email: 'mike@agency.com',
    role: 'Frontend Developer',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Next.js', 'CSS/SCSS'],
    availability: 'low' as const,
    activeProjects: 6,
    initials: 'MT',
  },
  {
    id: '4',
    name: 'Lisa Chen',
    email: 'lisa@agency.com',
    role: 'Backend Developer',
    skills: ['Node.js', 'PostgreSQL', 'AWS', 'API Design', 'Docker'],
    availability: 'high' as const,
    activeProjects: 3,
    avatar: '/placeholder-avatar.jpg',
    initials: 'LC',
  },
  {
    id: '5',
    name: 'Alex Rodriguez',
    email: 'alex@agency.com',
    role: 'UI Designer',
    skills: ['Visual Design', 'Typography', 'Illustration', 'Branding', 'Photoshop'],
    availability: 'medium' as const,
    activeProjects: 2,
    avatar: '/placeholder-avatar.jpg',
    initials: 'AR',
  },
  {
    id: '6',
    name: 'Emily Smith',
    email: 'emily@agency.com',
    role: 'Content Strategist',
    skills: ['Content Strategy', 'Copywriting', 'SEO', 'Content Marketing'],
    availability: 'high' as const,
    activeProjects: 5,
    initials: 'ES',
  },
];